### ISSUE TITLE
Improvement: add support for nested labels

### ISSUE THREAD

**Issue by hobovsky** [codewars/ocaml#3]
After #2 gets improved or merged, the event listener could be extended with support for nested `TestLabel` tests (not to be confused with nested test groups):

```ocaml
"Nested labels" >::: [
          "Outer label" >: ("Inner label" >: ("Tests with nested labels" >::: [
            TestCase (fun _ -> assert_equal false (is_even 100) ~msg:"Incorrect answer for n=100" ~printer: string_of_bool);
            TestCase (fun _ -> assert_equal false (is_even 100) ~msg:"Incorrect answer for n=100" ~printer: string_of_bool);          
            
          ]))
        ]
```

Such construct should not be too common, nonetheless OUnit supports it, it should not be difficult to support it in the listener, and currently the listener omits outer labels and displays only the innermost one.

**Comment by monadius** [comment]
I also suggest to print test duration after `<COMPLETEDIN::>`. Time values can be retrieved with `Unix.gettimeofday ()`.
