### ISSUE TITLE
Do not concatenate solution, preloaded, and test code

### ISSUE THREAD

**Issue by monadius** [codewars/ocaml#4]
It should be possible to have 3 separate files: `preloaded.ml`, `solution.ml`, and `tests.ml`. It will be necessary to manually import preloaded code with `open Preloaded` (or using the `Preloaded.` prefix) and solution with `open Solution`. But all line numbers in error and warning messages will be correct for both user code and tests.

**Comment by monadius** [comment]
I think it is better to update the OCaml version (the latest version is OCaml 4.13.1; but OCaml 4.14 should be released pretty soon) and fix this issue for a new OCaml version only.

**Comment by kazk** [comment]
Yeah, I have `TODO` comment somewhere. It'll be a breaking change, so a new version is necessary.

**Comment by kazk** [comment]
Separate issue, but I also want to manage dependencies properly.

**Comment by monadius** [comment]
I can prepare an image for a new OCaml version. Or should I wait until OCaml 4.14 is released? I don't think there will be a big difference between OCaml 4.14 and OCaml 4.13.1.

**Comment by kazk** [comment]
Thanks! I want #3 merged first, so we can freeze 4.07 and move to 4.13.1. We don't need to wait for 4.14.

**Comment by phreppo** [comment]
OCaml 5.0.0  [has been just released](https://ocaml.org/news/ocaml-5.0). Maybe it is worth updating directly to this major version.

**Comment by kazk** [comment]
Fixed in #6.
OCaml 5.0.0 will be deployed next week.
